name: lighter/darker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61363
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dadada'
    - '#aaaaaa'
    - '#000000'
    - '#5a5a5a'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
