name: lighter darker
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25649
title: l/d
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fedf4c'
    - '#fcfcfc'
    - '#6b6b6b'
    - '#c7c7c7'
  brandStrength: 0.25094073894433677
  lightness: 0.481247681658715
  saturation: 0.9515119902789593
  rhythmicContrast: 0.8138497250620276
purpose: []
